// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: internal/controller/grpc/proto/customer.proto

package grpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetApiKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *GetApiKeyRequest) Reset() {
	*x = GetApiKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyRequest) ProtoMessage() {}

func (x *GetApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyRequest.ProtoReflect.Descriptor instead.
func (*GetApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_controller_grpc_proto_customer_proto_rawDescGZIP(), []int{0}
}

func (x *GetApiKeyRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type GetApiKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey string `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty"`
}

func (x *GetApiKeyResponse) Reset() {
	*x = GetApiKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyResponse) ProtoMessage() {}

func (x *GetApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyResponse.ProtoReflect.Descriptor instead.
func (*GetApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_controller_grpc_proto_customer_proto_rawDescGZIP(), []int{1}
}

func (x *GetApiKeyResponse) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

type SetApiKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Apikey     string `protobuf:"bytes,2,opt,name=apikey,proto3" json:"apikey,omitempty"`
}

func (x *SetApiKeyRequest) Reset() {
	*x = SetApiKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApiKeyRequest) ProtoMessage() {}

func (x *SetApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApiKeyRequest.ProtoReflect.Descriptor instead.
func (*SetApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_controller_grpc_proto_customer_proto_rawDescGZIP(), []int{2}
}

func (x *SetApiKeyRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SetApiKeyRequest) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

type SetApiKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey string `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty"`
}

func (x *SetApiKeyResponse) Reset() {
	*x = SetApiKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApiKeyResponse) ProtoMessage() {}

func (x *SetApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApiKeyResponse.ProtoReflect.Descriptor instead.
func (*SetApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_controller_grpc_proto_customer_proto_rawDescGZIP(), []int{3}
}

func (x *SetApiKeyResponse) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

type GetCustomerUUIDByUserNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *GetCustomerUUIDByUserNameRequest) Reset() {
	*x = GetCustomerUUIDByUserNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerUUIDByUserNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerUUIDByUserNameRequest) ProtoMessage() {}

func (x *GetCustomerUUIDByUserNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerUUIDByUserNameRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerUUIDByUserNameRequest) Descriptor() ([]byte, []int) {
	return file_internal_controller_grpc_proto_customer_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerUUIDByUserNameRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetCustomerUUIDByUserNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerUuid string `protobuf:"bytes,1,opt,name=customer_uuid,json=customerUuid,proto3" json:"customer_uuid,omitempty"`
}

func (x *GetCustomerUUIDByUserNameResponse) Reset() {
	*x = GetCustomerUUIDByUserNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerUUIDByUserNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerUUIDByUserNameResponse) ProtoMessage() {}

func (x *GetCustomerUUIDByUserNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_grpc_proto_customer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerUUIDByUserNameResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerUUIDByUserNameResponse) Descriptor() ([]byte, []int) {
	return file_internal_controller_grpc_proto_customer_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomerUUIDByUserNameResponse) GetCustomerUuid() string {
	if x != nil {
		return x.CustomerUuid
	}
	return ""
}

var File_internal_controller_grpc_proto_customer_proto protoreflect.FileDescriptor

var file_internal_controller_grpc_proto_customer_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x22, 0x4b, 0x0a,
	0x10, 0x53, 0x65, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x65,
	0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x22, 0x3f, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x32, 0x9e, 0x02, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12,
	0x4a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x09, 0x53,
	0x65, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7a, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x55, 0x49,
	0x44, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_controller_grpc_proto_customer_proto_rawDescOnce sync.Once
	file_internal_controller_grpc_proto_customer_proto_rawDescData = file_internal_controller_grpc_proto_customer_proto_rawDesc
)

func file_internal_controller_grpc_proto_customer_proto_rawDescGZIP() []byte {
	file_internal_controller_grpc_proto_customer_proto_rawDescOnce.Do(func() {
		file_internal_controller_grpc_proto_customer_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_controller_grpc_proto_customer_proto_rawDescData)
	})
	return file_internal_controller_grpc_proto_customer_proto_rawDescData
}

var file_internal_controller_grpc_proto_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_controller_grpc_proto_customer_proto_goTypes = []interface{}{
	(*GetApiKeyRequest)(nil),                  // 0: grpcserver.GetApiKeyRequest
	(*GetApiKeyResponse)(nil),                 // 1: grpcserver.GetApiKeyResponse
	(*SetApiKeyRequest)(nil),                  // 2: grpcserver.SetApiKeyRequest
	(*SetApiKeyResponse)(nil),                 // 3: grpcserver.SetApiKeyResponse
	(*GetCustomerUUIDByUserNameRequest)(nil),  // 4: grpcserver.GetCustomerUUIDByUserNameRequest
	(*GetCustomerUUIDByUserNameResponse)(nil), // 5: grpcserver.GetCustomerUUIDByUserNameResponse
}
var file_internal_controller_grpc_proto_customer_proto_depIdxs = []int32{
	0, // 0: grpcserver.customer.GetApiKey:input_type -> grpcserver.GetApiKeyRequest
	2, // 1: grpcserver.customer.SetApiKey:input_type -> grpcserver.SetApiKeyRequest
	4, // 2: grpcserver.customer.GetCustomerUUIDByUserName:input_type -> grpcserver.GetCustomerUUIDByUserNameRequest
	1, // 3: grpcserver.customer.GetApiKey:output_type -> grpcserver.GetApiKeyResponse
	3, // 4: grpcserver.customer.SetApiKey:output_type -> grpcserver.SetApiKeyResponse
	5, // 5: grpcserver.customer.GetCustomerUUIDByUserName:output_type -> grpcserver.GetCustomerUUIDByUserNameResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_controller_grpc_proto_customer_proto_init() }
func file_internal_controller_grpc_proto_customer_proto_init() {
	if File_internal_controller_grpc_proto_customer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_controller_grpc_proto_customer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApiKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_grpc_proto_customer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApiKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_grpc_proto_customer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetApiKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_grpc_proto_customer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetApiKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_grpc_proto_customer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerUUIDByUserNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_controller_grpc_proto_customer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerUUIDByUserNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_controller_grpc_proto_customer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_controller_grpc_proto_customer_proto_goTypes,
		DependencyIndexes: file_internal_controller_grpc_proto_customer_proto_depIdxs,
		MessageInfos:      file_internal_controller_grpc_proto_customer_proto_msgTypes,
	}.Build()
	File_internal_controller_grpc_proto_customer_proto = out.File
	file_internal_controller_grpc_proto_customer_proto_rawDesc = nil
	file_internal_controller_grpc_proto_customer_proto_goTypes = nil
	file_internal_controller_grpc_proto_customer_proto_depIdxs = nil
}
